# Generated by Django 5.2 on 2025-04-09 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('survey', 'Survey'), ('interview', 'Interview')], max_length=50)),
                ('stage', models.CharField(choices=[('initiating', 'Initiating'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=50)),
                ('maturity_level', models.CharField(choices=[('Emerging', 'Emerging'), ('Tactical', 'Tactical'), ('Strategic', 'Strategic'), ('Transformational', 'Transformational')], default='Emerging', max_length=20)),
                ('strategy_score', models.FloatField(default=0)),
                ('execution_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights.client')),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_text', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='PillarScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillar_scores', to='insights.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(max_length=100)),
                ('recommendation_text', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='insights.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('consultant', 'Consultant'), ('client', 'Client')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

# touched on 2025-05-27T15:28:48.238708Z
# touched on 2025-05-27T15:29:05.130012Z
# touched on 2025-05-27T15:29:07.768707Z
# touched on 2025-08-14T21:16:30.688120Z
# touched on 2025-08-14T21:16:36.923631Z
# touched on 2025-08-14T21:16:38.964894Z
# touched on 2025-08-14T21:16:43.274497Z
# touched on 2025-08-14T21:16:58.063138Z
# touched on 2025-08-14T21:17:51.595827Z
# touched on 2025-08-14T21:17:55.705817Z
# touched on 2025-08-14T21:18:20.559507Z
# touched on 2025-08-14T21:18:22.659376Z
# touched on 2025-08-14T21:18:30.912884Z
# touched on 2025-08-14T21:18:47.409974Z
# touched on 2025-08-14T21:19:00.078774Z
# touched on 2025-08-14T21:19:04.388785Z
# touched on 2025-08-14T21:19:12.728036Z
# touched on 2025-08-14T21:19:35.808434Z
# touched on 2025-08-14T21:19:37.987958Z
# touched on 2025-08-14T21:20:04.568201Z
# touched on 2025-08-14T21:20:13.172916Z
# touched on 2025-08-14T21:20:20.209037Z
# touched on 2025-08-14T21:20:35.064125Z
# touched on 2025-08-14T21:20:41.381229Z