# Generated by Django 5.2 on 2025-04-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(max_length=100)),
                ('quote_text', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='insights.assessment')),
            ],
        ),
    ]

# touched on 2025-05-27T15:29:02.327358Z
# touched on 2025-05-27T15:29:07.768872Z
# touched on 2025-05-27T15:29:10.581028Z
# touched on 2025-08-14T21:16:34.769067Z
# touched on 2025-08-14T21:16:43.274854Z
# touched on 2025-08-14T21:16:47.630616Z
# touched on 2025-08-14T21:16:53.869036Z