# Generated by Django 5.2 on 2025-04-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(max_length=100)),
                ('quote_text', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='insights.assessment')),
            ],
        ),
    ]

# touched on 2025-05-27T15:29:02.327358Z
# touched on 2025-05-27T15:29:07.768872Z
# touched on 2025-05-27T15:29:10.581028Z
# touched on 2025-08-14T21:16:34.769067Z
# touched on 2025-08-14T21:16:43.274854Z
# touched on 2025-08-14T21:16:47.630616Z
# touched on 2025-08-14T21:16:53.869036Z
# touched on 2025-08-14T21:17:09.186126Z
# touched on 2025-08-14T21:17:34.880066Z
# touched on 2025-08-14T21:17:49.483261Z
# touched on 2025-08-14T21:18:06.133242Z
# touched on 2025-08-14T21:18:22.659594Z
# touched on 2025-08-14T21:18:37.188080Z
# touched on 2025-08-14T21:18:45.293496Z
# touched on 2025-08-14T21:18:58.069589Z
# touched on 2025-08-14T21:19:02.237254Z
# touched on 2025-08-14T21:19:12.728272Z
# touched on 2025-08-14T21:19:27.489103Z
# touched on 2025-08-14T21:19:31.648975Z
# touched on 2025-08-14T21:19:37.988083Z
# touched on 2025-08-14T21:20:06.948477Z
# touched on 2025-08-14T21:20:11.101552Z
# touched on 2025-08-14T21:20:20.209740Z