# Generated by Django 5.2 on 2025-04-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_quote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]

# touched on 2025-05-27T15:29:02.323507Z
# touched on 2025-08-14T21:16:24.128928Z
# touched on 2025-08-14T21:16:26.365705Z
# touched on 2025-08-14T21:16:28.595196Z
# touched on 2025-08-14T21:16:53.869316Z
# touched on 2025-08-14T21:16:55.964035Z
# touched on 2025-08-14T21:17:32.684184Z
# touched on 2025-08-14T21:17:49.483506Z
# touched on 2025-08-14T21:18:18.397723Z
# touched on 2025-08-14T21:18:24.754561Z
# touched on 2025-08-14T21:19:02.236754Z
# touched on 2025-08-14T21:19:10.595099Z
# touched on 2025-08-14T21:19:17.131379Z
# touched on 2025-08-14T21:19:37.988551Z
# touched on 2025-08-14T21:20:09.035791Z
# touched on 2025-08-14T21:20:47.737728Z
# touched on 2025-08-14T21:21:17.609776Z
# touched on 2025-08-14T21:21:25.936446Z