# Generated by Django 5.2 on 2025-04-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_scores', to='insights.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(max_length=100)),
                ('matched_phrase', models.CharField(max_length=255)),
                ('input_phrase', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='insights.assessment')),
            ],
        ),
    ]

# touched on 2025-05-27T15:29:05.130444Z
# touched on 2025-08-14T21:16:47.629720Z
# touched on 2025-08-14T21:16:58.063253Z
# touched on 2025-08-14T21:17:04.785885Z
# touched on 2025-08-14T21:17:20.133488Z
# touched on 2025-08-14T21:18:10.319978Z
# touched on 2025-08-14T21:18:14.391473Z
# touched on 2025-08-14T21:18:16.428564Z
# touched on 2025-08-14T21:18:28.903025Z
# touched on 2025-08-14T21:18:32.927572Z
# touched on 2025-08-14T21:18:45.293956Z
# touched on 2025-08-14T21:18:51.586342Z
# touched on 2025-08-14T21:19:31.648621Z
# touched on 2025-08-14T21:19:48.298892Z
# touched on 2025-08-14T21:20:04.568352Z
# touched on 2025-08-14T21:20:06.948245Z
# touched on 2025-08-14T21:20:33.002489Z
# touched on 2025-08-14T21:20:37.214600Z
# touched on 2025-08-14T21:21:32.052681Z